// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Project2;

{ITE} {DFMFileType} {Unit1.dfm}
{ITE} {DFMFileType} {Unit10.dfm}
{ITE} {DFMFileType} {Unit13.dfm}
{ITE} {DFMFileType} {Unit14.dfm}
{ITE} {DFMFileType} {Unit15.dfm}
{ITE} {DFMFileType} {Unit16.dfm}
{ITE} {DFMFileType} {Unit17.dfm}
{ITE} {DFMFileType} {Unit18.dfm}
{ITE} {DFMFileType} {Unit19.dfm}
{ITE} {DFMFileType} {Unit2.dfm}
{ITE} {DFMFileType} {Unit21.dfm}
{ITE} {DFMFileType} {Unit22.dfm}
{ITE} {DFMFileType} {Unit26.dfm}
{ITE} {DFMFileType} {Unit27.dfm}
{ITE} {DFMFileType} {Unit28.dfm}
{ITE} {DFMFileType} {Unit3.dfm}
{ITE} {DFMFileType} {Unit4.dfm}
{ITE} {DFMFileType} {Unit5.dfm}
{ITE} {DFMFileType} {Unit6.dfm}
{ITE} {DFMFileType} {Unit7.dfm}
{ITE} {DFMFileType} {Unit8.dfm}
{ITE} {DFMFileType} {Unit9.dfm}
{ITE} {RCFileType} {Project2_DRC.rc}

{$R 'Unit1.dfm' 'Form1:TForm'}
{$R 'Unit10.dfm' 'Form10:TForm'}
{$R 'Unit13.dfm' 'Form13:TForm'}
{$R 'Unit14.dfm' 'Form14:TForm'}
{$R 'Unit15.dfm' 'Form15:TForm'}
{$R 'Unit16.dfm' 'Form16:TForm'}
{$R 'Unit17.dfm' 'Form17:TForm'}
{$R 'Unit18.dfm' 'Form18:TForm'}
{$R 'Unit19.dfm' 'Form19:TForm'}
{$R 'Unit2.dfm' 'Form2:TForm'}
{$R 'Unit21.dfm' 'Form21:TForm'}
{$R 'Unit22.dfm' 'Form22:TForm'}
{$R 'Unit26.dfm' 'Form26:TForm'}
{$R 'Unit27.dfm' 'Form27:TForm'}
{$R 'Unit28.dfm' 'Form28:TForm'}
{$R 'Unit3.dfm' 'Form3:TForm'}
{$R 'Unit4.dfm' 'Form4:TForm'}
{$R 'Unit5.dfm' 'Form5:TForm'}
{$R 'Unit6.dfm' 'Form6:TForm'}
{$R 'Unit7.dfm' 'Form7:TForm'}
{$R 'Unit8.dfm' 'Form8:TForm'}
{$R 'Unit9.dfm' 'Form9:TForm'}
{$R 'Project2_DRC.res' 'Project2_DRC.rc'}

{$E HRV}

begin
end.
