// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Project2;

{ITE} {DFMFileType} {FormUnit1.dfm}
{ITE} {DFMFileType} {WebModuleUnit1.dfm}
{ITE} {RCFileType} {Project2_DRC.rc}

{$R 'FormUnit1.dfm' 'Form1:TForm'}
{$R 'WebModuleUnit1.dfm' 'WebModule1:TForm'}
{$R 'Project2_DRC.res' 'Project2_DRC.rc'}

{$E HRV}

begin
end.
